name: Build NeoFreeBird

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the IPA"
        default: ""
        required: true
        type: string
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v6.0.1
        with:
          repository: KieranBLK/Neo
          path: main
          ref: ${{ github.ref }}
          submodules: recursive
          
      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
          
      - name: Download and Validate IPA
        id: ipa
        run: |
          IPA_URL="${{ inputs.ipa_url }}"

          # Extract filename from URL
          FILE_NAME=$(basename "${IPA_URL%%\?*}")
          NAME_NO_EXT="${FILE_NAME%.*}"
          echo "IPA file name: $FILE_NAME"
          
          wget "$IPA_URL" --no-verbose -O "$NAME_NO_EXT".ipa
          file_type=$(file --mime-type -b "$NAME_NO_EXT".ipa)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
          exit 1
          fi
          
          # Expected format: com.atebits.Tweetie2_##.##.ipa
          # Extract version number
          X_VERSION=$(echo "$NAME_NO_EXT" | grep -oE '[0-9]+(\.[0-9]+)+')
          echo "Twitter version detected: $X_VERSION"
          # Expose it to later steps
          echo "x_version=$X_VERSION" >> "$GITHUB_OUTPUT"

          #Rename to "twitter.ipa" for tweak injection later on
          mv "$NAME_NO_EXT".ipa twitter.ipa  
          
      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environment variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
          
      - name: Cache Theos
        id: theos
        uses: actions/cache@v5.0.2
        env:
          cache-name: theos_cache_13c2237
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v6.0.1
        with:
          repository: theos/theos
          ref: 13c22376b5d83ff759c1993de0a861e673aa522b
          path: theos
          submodules: recursive
          
      - name: Download iOS SDK
        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks
          
      - name: Install Cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
      
      - name: Clone Tweak
        run: git clone --quiet --depth=1 https://github.com/NeoFreeBird/tweak.git
      
      - name: Build NFB
        run: |
          cd tweak
          make clean package DEBUG=0 FINALPACKAGE=1
          
      - name: Copy Package to Directory
        run: |
         mkdir -p main
         find tweak -type f -name "*.deb" -exec cp {} main \;
         echo "deb copied to main"
         ls -lh main

      - name: Patch and Inject
        run: |
          # Patch
          PATCH_SRC="main/assets/main"
          if [ -d "${PATCH_SRC}" ]; then
          rsync -av "${PATCH_SRC}/" main/tmp/Payload/Twitter.app/
          fi

          # Inject 
          for f in main/*.deb; do
            if [ -f "$f" ]; then
              tweaks="$tweaks $f"
            fi
          done
          cyan -i twitter.ipa -o NeoFreeBird_${{ steps.ipa.outputs.x_version }}.ipa

      - name: Upload Draft to GitHub Releases
        uses: softprops/action-gh-release@v2.0.1
        with:
          tag_name: NFB-${{ github.run_number }}
          name: NeoFreeBird_${{ steps.ipa.outputs.x_version }}.ipa
          files: NeoFreeBird_${{ steps.ipa.outputs.x_version }}.ipa
          draft: true
      
      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
          
