name: Build Neo

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the IPA"
        default: ""
        required: true
        type: string
        
      sdk_version:
        description: "Theos SDK Version"
        default: "16.5"
        required: true
        type: string
        
      target_version:
        description: "Target iOS Version"
        default: "14.0"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-inject:
    name:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: sdk_version,target_version
          
      - name: Download and Validate IPA
        id: ipa
        run: |
          IPA_URL="${{ inputs.ipa_url }}"

          # Extract filename from URL
          FILE_NAME=$(basename "${IPA_URL%%\?*}")
          NAME_NO_EXT="${FILE_NAME%.*}"
          echo "IPA file name: $FILE_NAME"
          
          wget "$IPA_URL" --no-verbose -O "$NAME_NO_EXT".ipa
          file_type=$(file --mime-type -b "$NAME_NO_EXT".ipa)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
          exit 1
          fi
          
          # Expected format: com.atebits.Tweetie2_##.##.ipa
          # Extract version number
          X_VERSION=$(echo "$NAME_NO_EXT" | grep -oE '[0-9]+(\.[0-9]+)+')
          echo "Twitter version detected: $X_VERSION"
          # Expose it to later steps
          echo "x_version=$X_VERSION" >> "$GITHUB_OUTPUT"
          
      - name: Install Dependencies
        run: brew install make dpkg ldid

      - name: Set PATH environment variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
          
      - name: Cache Theos
        id: theos
        uses: actions/cache@v5.0.2
        env:
          cache-name: theos_cache_13c2237
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v6.0.1
        with:
          repository: theos/theos
          ref: 13c22376b5d83ff759c1993de0a861e673aa522b
          path: theos
          submodules: recursive
          
      - name: Download iOS SDK
        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks
          
      - name: Install Cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Build tweak with Theos
        run: |
          cd tweak
          sed -i '' "s/^TARGET.*$/TARGET := iphone:clang:${{ inputs.sdk_version }}:${{ inputs.target_version }}/" Makefile
          make package

      - name: Copy deb to main/packages
        run: |
         mkdir -p main/packages
         find tweak -type f -name "*.deb" -exec cp {} main/packages/ \;
         echo "Files in main/packages after copy:"
         ls -lh main/packages

      - name: Apply patches and inject tweak
        run: |
          # Apply patches to the extracted Twitter.app
          PATCH_SRC="main/assets/main"
          if [ -d "${PATCH_SRC}" ]; then
          rsync -av "${PATCH_SRC}/" main/tmp/Payload/Twitter.app/
          fi
    
          # Find the .deb file in main/packages
          DEB_FILE=$(find main/packages -name "*.deb" -type f | head -n1)
          if [ -z "$DEB_FILE" ]; then
          echo "âŒ No .deb file found in main/packages"
          exit 1
          fi
    
          # Use cyan to inject the tweak
          cd main/tmp
          zip -qr ../packages/temp.ipa Payload
          cd ..
          cyan -i packages/temp.ipa -f "$DEB_FILE" -o packages/NeoFreeBird_${{ github.run_id }}_${{ steps.ipa.outputs.X_VERSION }}.ipa
    
          # Create .tipa copy
          cp packages/NeoFreeBird_${{ github.run_id }}_${{ steps.ipa.outputs.X_VERSION }}.ipa packages/NeoFreeBird_${{ github.run_id }}_${{ steps.ipa.outputs.X_VERSION }}.tipa

      - name: Pass package name
        id: package_name
        run: |
          echo "ipa_package=NeoFreeBird_${{ github.run_id }}_${{ steps.ipa.outputs.X_VERSION }}.ipa" >> "$GITHUB_OUTPUT"
          echo "tipa_package=NeoFreeBird_${{ github.run_id }}_${{ steps.ipa.outputs.X_VERSION }}.tipa" >> "$GITHUB_OUTPUT"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: NeoFreeBird-injected-IPA
          path: main/packages/${{ steps.package_name.outputs.ipa_package }}
          if-no-files-found: error

      - name: Upload TIPA
        uses: actions/upload-artifact@v4
        with:
          name: NeoFreeBird-injected-TIPA
          path: main/packages/${{ steps.package_name.outputs.tipa_package }}
          if-no-files-found: error
